import type { Metadata } from 'next';
import './globals.css';
import { bodyFont, displayFont, serifFont } from '@/lib/fonts';
import { SmoothScroll } from '@/components/layout/SmoothScroll';
import { CustomCursor, NoiseOverlay } from '@/components/motion';
import { MetaPixel } from '@/components/analytics/MetaPixel';
import { BRAND } from '@/content/site';
import { SITE_URL } from '@/lib/seo/site-url';

/**
 * Root layout.
 *
 * `data-brand="productions"` is the site-wide default mood; any route or section
 * overrides it with BrandProvider (063 Society runs in elegant mode).
 *
 * The three font variables are attached here so every brand map in tokens.css
 * can resolve --display-family regardless of which mode is active.
 */

/**
 * ⚠️ OWNERSHIP SEAM — read before adding metadata here.
 *
 * This is the metadata *baseline*, Developer 1's Milestone 4 EASY task
 * ("favicon, browser tab titles and the social share image", Task Division
 * Rev 2 p.5). It sets the things that must be defined exactly once for the
 * whole site: the title template every tab title flows through, metadataBase,
 * and the default share card.
 *
 * The full SEO pass — a written title and description for EVERY page, sitemap,
 * robots, page-speed — is Developer 2's Milestone 4 HARD task. So there are
 * deliberately no per-page metadata exports from me: Developer 2 adds
 * `export const metadata` to each page and the template below wraps it, e.g.
 * `title: 'Services'` renders as "Services — ZERO-SIXTY-THREE PRODUCTIONS".
 *
 * Icons and the share image are wired automatically by file convention from
 * app/favicon.ico, app/icon.png, app/apple-icon.png and app/opengraph-image.png
 * (generated by scripts/generate-brand-images.mjs) — no `icons` field needed.
 */
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: BRAND.full,
    template: `%s — ${BRAND.full}`,
  },
  // Real client copy, verbatim from the live site — not a placeholder.
  description: BRAND.tagline,
  applicationName: BRAND.full,
  openGraph: {
    type: 'website',
    siteName: BRAND.full,
    title: BRAND.full,
    description: BRAND.tagline,
    url: '/',
    locale: 'en_AE',
  },
  twitter: {
    card: 'summary_large_image',
    title: BRAND.full,
    description: BRAND.tagline,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      data-brand="productions"
      className={`${displayFont.variable} ${serifFont.variable} ${bodyFont.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased">
        {/* Lenis — self-disables under prefers-reduced-motion. */}
        <SmoothScroll />

        {children}

        {/* Decoration only: both remove themselves on touch / reduced motion. */}
        <NoiseOverlay />
        <CustomCursor />

        {/* Renders nothing until NEXT_PUBLIC_META_PIXEL_ID is set (BLOCKER B15). */}
        <MetaPixel />
      </body>
    </html>
  );
}
